title: "Ark Blog"
description: "기록하고 공유하는 공간입니다."
url: "https://ark-poiop.github.io"
baseurl: ""

theme: null
locale: "ko-KR"
show_sidebar_nav: true

author:
  name: "Ark"
  avatar: "/assets/images/profile.png"
  bio: "실패해도 도전하는 블로거입니다."

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5
paginate_path: /page:num/

collections:
  pages:
    output: true
    permalink: /:path/
