title: "포이옵의 블로그"
description: "기록과 공유의 공간"
url: "https://ark-poiop.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
locale: "ko-KR"

author:
  name: "포이옵"
  avatar: "/assets/images/profile.png"
  bio: "배우고 기록하며, 만드는 사람"